<?php

namespace Acme\Bundle\ImageGalleryBundle\Repository;

/**
 * Main_ImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Main_ImgRepository extends \Doctrine\ORM\EntityRepository
{
}
